### ISSUE TITLE
配置文件问题

### ISSUE THREAD

**Issue by yueliuLEE** [AnyPortal/AnyPortal#1]
大佬，你好，这个软件不能自动解析base64编码吗？使用机场订阅链接无法使用
配置文件有没有具体的示例参考呢？

**Comment by AnyPortal** [comment]
Currently only one [self-designed remote protocol](https://github.com/AnyPortal/AnyPortal/blob/main/docs/subscription.md) is implemented. It's still in the early stages and may be subject to change.

If you have a specific protocol in mind, please share its specification.

**Comment by yueliuLEE** [comment]
For example, for common protocols such as vless and vmess, can you add a function to automatically generate corresponding configuration files based on these protocols, so that they are more convenient to use?

**Comment by AnyPortal** [comment]
Sure it can be managed, and we will implement these specifications if it proves official/popular. By specification I actually mean something like [sip008](https://shadowsocks.org/doc/sip008.html). Do you have any particular one in mind?

**Comment by yueliuLEE** [comment]
I'm just an amateur user, so I don't have any good ideas. thanks

**Comment by AnyPortal** [comment]
Well don't be frustrated. The problem here is that we can't just support some subscription format without knowing what fields to expect.
You are welcomed to provide more information about the format, or close this issue.
