### ISSUE TITLE
合作请求

### ISSUE THREAD

**Issue by Erfan-Fazeli** [AnyPortal/AnyPortal#2]
你好 之前想在App Store发布一个基于自己的sign-box核心的应用，但是遇到了获取苹果开发者账号的问题，其实除了99美元的年费之外，还需要注册一个官方的。公司（我不确定）。 如果我可以成为财务赞助商，您可以在 App Store 中发布此应用程序的 2 个版本吗？一个以您的应用程序的名称开源，另一个以我选择的名称进行一些更改。 由于我没有注册公司，所以无法在应用商店发布任何应用

**Comment by AnyPortal** [comment]
Thanks for your offer but our current decision is no.
Send us an [email](anyportal.dev@gmail.com) if you'd like to get notified should we change our policy in the future.
We will actively work on solving Apple's developer license problem nonetheless, thanks for your support!
