### ISSUE TITLE
sample configuration

### ISSUE THREAD

**Issue by LonUp** [AnyPortal/AnyPortal#3]
I have a problem entering the subscription. And I tested it with base 64, yaml, singbox, V2ray and Json, and I get an error. Can you provide a sample configuration so that I can create the input file or subscription link according to it?

**Comment by AnyPortal** [comment]
There are two kinds of remote subscriptions.
- A standalone remote profile is a url pointing to a config, usually a v2ray config.json.
- A [remote profile group subscription](https://github.com/AnyPortal/AnyPortal/blob/main/docs/subscription.md), which is still an experimental format and we are considering adding more fields to it.

We plan to implement common subscription formats but are slightly confused now.

- We noticed that v2ray has its own [subscription manager](https://www.v2fly.org/en_US/v5/config/service/subscription.html#subscriptionimportobject) with support to Base64URLLine, Yaml2Json+JsonFieldArray, DataURLSingle. Are these the formats you mentioned?

**Comment by LonUp** [comment]
> Are these the formats you mentioned?
 
 Yes, I meant these formats.  
Thank you for the response, I understand now.
